---
# tasks file for database
- name: update apt
  become: yes
  shell: apt update

- name: install mysql
  become: yes
  apt:
    name: mysql-server
    state: present

- name: copy mysql config
  become: yes
  copy:
    src: init.sql
    dest: /home/ubuntu/init.sql

- name: copy mysql config
  become: yes
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: restart mysql
  become: yes
  systemd:
    name: mysql
    state: restarted
